{
 "title": "Nginx",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "2022-03-14T06:57:30.000Z", "to": "2022-03-14T07:07:30.000Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[2m])) by (le))*1000",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[2m])) by (le))*1000",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[2m])) by (le))*1000",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Nginx RPS by status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\"}[$interval])) by (status)",
     "legendFormat": "status - {{status}}"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\",status=~\"5.+\"}[2m]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\",status=~\"4.+\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}