{
 "title": "Billing-app",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Billing-app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(app_request_latency_seconds_count{service=\"billing-app\", namespace=\"$namespace\"}[$interval])) by (exported_endpoint, method)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status)(increase(app_request_latency_seconds_count{status=~\"5.+\"}[$interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status)(increase(app_request_latency_seconds_count{status=~\"4.+\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_request_latency_seconds_bucket{service=\"billing-app\", namespace=\"$namespace\", exported_endpoint=~\".*/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.5 {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket{service=\"billing-app\", namespace=\"$namespace\", exported_endpoint=~\".*/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.95 {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_request_latency_seconds_bucket{service=\"billing-app\", namespace=\"$namespace\", exported_endpoint=~\".*/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.99 {{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_request_latency_seconds_bucket{service=\"billing-app\", namespace=\"$namespace\", exported_endpoint=~\".*/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket{service=\"billing-app\", namespace=\"$namespace\", exported_endpoint=~\".*/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_request_latency_seconds_bucket{service=\"billing-app\", namespace=\"$namespace\", exported_endpoint=~\".*/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  { "title": "Pod Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"billing-app-chart\"}) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"billing-app-chart\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}