apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-app-dashboard
  labels:
    grafana-dashboard: "1"
data:
  billing-app-dashboard.json: |-
{{ .Files.Get "files/grafana-dashboard.json" | indent 4 }}
