apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-app-dashboard
  labels:
    grafana-dashboard: "1"
data:
  delivery-app-dashboard.json: |-
{{ .Files.Get "files/grafana-dashboard.json" | indent 4 }}
