apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-routes
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/auth/api/`)
      services:
        - name: {{ index .Values "auth-app-chart" "fullnameOverride" }}
          namespace: {{ .Release.Namespace }}
          port: {{ index .Values "auth-app-chart" "service" "port" }}
      middlewares:
        - name: strip-service-prefixes
          namespace: {{ .Release.Namespace }}
    - kind: Rule
      match: PathPrefix(`/user/api/v1/register`)
      services:
        - name: {{ index .Values "user-app-chart" "fullnameOverride" }}
          namespace: {{ .Release.Namespace }}
          port: {{ index .Values "user-app-chart" "service" "port" }}
      middlewares:
        - name: strip-service-prefixes
          namespace: {{ .Release.Namespace }}
    - kind: Rule
      match: PathPrefix(`/user/api/`)
      services:
        - name: {{ index .Values "user-app-chart" "fullnameOverride" }}
          namespace: {{ .Release.Namespace }}
          port: {{ index .Values "user-app-chart" "service" "port" }}
      middlewares:
        - name: strip-service-prefixes
          namespace: {{ .Release.Namespace }}
        - name: authentication
          namespace: {{ .Release.Namespace }}
    - kind: Rule
      match: PathPrefix(`/billing/api/`)
      services:
        - name: {{ index .Values "billing-app-chart" "fullnameOverride" }}
          namespace: {{ .Release.Namespace }}
          port: {{ index .Values "billing-app-chart" "service" "port" }}
      middlewares:
        - name: strip-service-prefixes
          namespace: {{ .Release.Namespace }}
        - name: authentication
          namespace: {{ .Release.Namespace }}
    - kind: Rule
      match: PathPrefix(`/lot/api/`)
      services:
        - name: {{ index .Values "lot-app-chart" "fullnameOverride" }}
          namespace: {{ .Release.Namespace }}
          port: {{ index .Values "lot-app-chart" "service" "port" }}
      middlewares:
        - name: strip-service-prefixes
          namespace: {{ .Release.Namespace }}
        - name: authentication
          namespace: {{ .Release.Namespace }}